name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  # Unit test
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: command-or-ctrl-key

      - name: run unit tests
        run: npm test
        working-directory: command-or-ctrl-key
        
